# Generated by Django 3.2.5 on 2021-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_degree', models.CharField(max_length=100)),
                ('doctor_address', models.CharField(max_length=200)),
                ('doctor_number', models.CharField(max_length=20)),
                ('doctor_email', models.CharField(max_length=30)),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_age', models.CharField(max_length=5)),
                ('patient_gender', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, default='NA')),
            ],
            options={
                'db_table': 'report_data',
            },
        ),
    ]
