# Generated by Django 3.2.5 on 2021-07-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_data',
            name='uuid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
