# Generated by Django 3.2.5 on 2021-07-08 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_report_data_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_data',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
