# Generated by Django 3.2.5 on 2021-07-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_data',
            name='tests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
